### Create a new complaint
POST http://localhost:3000/api/complaints
Content-Type: application/json

{
  "quarterNumber": "123",
  "name": "Jane Doe",
  "phone": "9876543210",
  "email": "jane@example.com",
  "complaintType": "Electrical",
  "urgency": "Regular",
  "complaint": "There are exposed wires in the bathroom.",
  "availabilityDate": "2024-07-10",
  "availabilityTime": "11 AM"
}


###

### Get all complaints
GET http://localhost:3000/api/complaints

###

### Update a complaint
PUT http://localhost:3000/api/complaints/8fd4bd08-8f07-4c80-8b41-b1418898e53c
Content-Type: application/json

{
  "status": "Resolved",
  "urgency": "Regular"
}


###

### Delete a complaint
DELETE http://localhost:3000/api/complaints/8fd4bd08-8f07-4c80-8b41-b1418898e53c

###

### Register a new worker
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "hilton",
  "name": "Paris Hilton",
  "phone": "9123456780",
  "email": "paris.hilton1@gmail.com",
  "password": "password123",
  "expertise": "Electrical"
}

###

### Worker login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "paris.hilton1@gmail.com",
  "password": "password123"
}